### ISSUE TITLE
Option to replace high resolution photo in camera roll with lower resolution

### ISSUE THREAD

**Issue by jmathai** [delightfulapp/delightful#7]
It'd be nice if the app had a setting that replaces the high resolution photo in the camera roll with a lower resolution (1024 or 1280) after it's been uploaded successfully. It would be an easy way to free up space on the phone without connecting any wires and creating a remote _copy_ in one step.

I believe the new iOS 8 APIs let you delete/create photos from the camera roll.

**Comment by patricksan** [comment]
Interesting....

**Comment by jmathai** [comment]
I finally freed up space no my phone by syncing with iPhoto but it sucks to have to do that all the time. Would be nice if an app did it for me. Extra points if it did it and stored in my Trovebox library.

**Comment by patricksan** [comment]
iCloud does that.

**Comment by jmathai** [comment]
I don't think I'll ever understand exactly how iCloud works.

**Comment by jmathai** [comment]
Works well in the latest build. What do you think about either having the setting be persistent under "settings" or remembering the last selected value?

I don't want to have to remember to always enable it on each upload :).

**Comment by jmathai** [comment]
Perfection.
